chris:
  name: Dr Christopher Burr
  description: Ethics Fellow
  avatar: https://github.com/chrisdburr.png
clau:
  name: Claudia Fischer
  description: Research Assistant
  avatar: https://github.com/claufischer.png
david:
  name: Professor David Leslie
  description: Director of Ethics and Responsible Innovation Research
  avatar: https://www.turing.ac.uk/sites/default/files/styles/people/public/2018-11/bio_pic_0.jpg?itok=0Ey8l0kg
